---
sidebar: sidebar 
permalink: migration/shift-toolkit-supported-versions.html 
keywords: netapp, vmware, esxi, vm, migration, openshift, virtualization, hyper-v, proxmox, software, support, shift, toolkit 
summary: 請確認您的 Windows 和 Linux 客戶作業系統、 ONTAP版本和虛擬機器管理程式是否受NetApp Shift Toolkit 支援。 
---
= NetApp Shift 工具包支援的版本
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
請確認您的 Windows 和 Linux 客戶作業系統、 ONTAP版本和虛擬機器管理程式是否受NetApp Shift Toolkit 支援。



== 支援的虛擬機器客戶作業系統

Shift Toolkit 支援以下 Windows 和 Linux 客戶作業系統，用於 VM 轉換。

.Windows作業系統
* Windows 10
* Windows 11
* Windows 伺服器 2016
* Windows 伺服器 2019
* Windows 伺服器 2022
* Windows 伺服器 2025


.Linux作業系統
* CentOS Linux 7.x
* Alma Linux 7.x
* Red Hat Enterprise Linux 7.2 或更高版本
* Red Hat Enterprise Linux 8.x
* 紅帽企業 Linux 9.x
* Ubuntu 2018
* Ubuntu 2022
* Ubuntu 2024
* Debian 12
* SUSE Linux Enterprise Server 12
* SUSE Linux Enterprise Server 15



NOTE: 不支援 CentOS Linux 和 Red Hat Enterprise Linux 版本 5 和 6。


NOTE: Windows Server 2008 未獲得官方支援。但是，轉換過程可能有效，有些客戶已經成功轉換了 Windows Server 2008 虛擬機器。遷移後，請手動更新 IP 位址，因為用於 IP 位址自動指派的 PowerShell 版本與 Windows Server 2008 不相容。



== 支援的 ONTAP 版本

Shift Toolkit 支援ONTAP 9.14.1 或更高版本。



== 支援的虛擬機器管理程序

Shift Toolkit 支援以下虛擬機器管理程式平台，用於虛擬機器遷移和轉換。


NOTE: 目前版本僅支援 Hyper-V、VMware、OpenShift 和 Oracle Virtualization 進行端對端虛擬機器遷移。對於 KVM 目標，僅支援磁碟轉換。

.VMware vSphere
Shift 工具包已通過 vSphere 7.0.3 或更高版本的驗證。

.微軟 Hyper-V
Shift 工具包已針對以下 Hyper-V 角色進行驗證：

* 在 Windows Server 2019 上執行的 Hyper-V 角色
* 在 Windows Server 2022 上執行的 Hyper-V 角色
* 在 Windows Server 2025 上執行的 Hyper-V 角色


.紅帽 OpenShift
Shift 工具包已針對運行 4.17 及更高版本的 Red Hat OpenShift 和 OpenShift Virtualization 進行了驗證。

.Oracle Linux 虛擬化管理器
Shift 工具包已針對下列 Oracle Linux Virtualization Manager 版本進行驗證：

* Oracle Linux Virtualization Manager 4.5 或更高版本
* Oracle Linux Virtualization Manager 主機必須安裝 ovirt-engine-4.5.4-1.el8 RPM 或更高版本。


.虛擬機
對於 KVM 目標，Shift Toolkit 僅支援磁碟格式轉換（VMDK 到 QCOW2 或 RAW）。從目標下拉式選單中選擇 KVM 時，不需要提供虛擬機器管理程式連線詳細資訊。轉換完成後，使用 QCOW2 磁碟在基於 KVM 的平台上配置虛擬機器。
