---
sidebar: sidebar 
permalink: proxmox/proxmox-ontap.html 
keywords: netapp, proxmox, proxmox ve, all-flash, nfs, iscsi, ontap, storage, aff 
summary: '使用 NAS 協定（NFS、SMB）和 SAN 協定（FC、iSCSI、NVMe）為 Proxmox 虛擬環境 (VE) 提供ONTAP儲存。選擇合適的協定特定步驟來設定 Proxmox VE 叢集的共用儲存。' 
---
= 了解 Proxmox VE 與NetApp ONTAP的儲存協議
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用 NAS 協定（NFS、SMB）和 SAN 協定（FC、iSCSI、NVMe）為 Proxmox 虛擬環境 (VE) 提供ONTAP儲存。選擇合適的協定特定步驟來設定 Proxmox VE 叢集的共用儲存。

確保 Proxmox VE 主機具有 FC、乙太網路或其他受支援的接口，並透過電纜連接到交換機，從而與ONTAP邏輯介面通訊。務必檢查 https://mysupport.netapp.com/matrix/#welcome["互通性矩陣工具"] 適用於支援的配置。範例場景的建立基於以下假設：每個 Proxmox VE 主機上都有兩張高速網路介面卡，這兩張卡連接在一起以建立綁定接口，從而實現容錯和效能。所有網路流量（包括主機管理、虛擬機器/容器流量和儲存存取）均使用相同的上行鏈路連接。當有更多網路介面可用時，請考慮將儲存流量與其他類型的流量分開。

有關ONTAP儲存架構和支援的儲存類型的信息，請參閱 link:proxmox-ontap-architecture.html["了解 Proxmox VE 的ONTAP儲存架構"] 和 link:proxmox-storage-types.html["了解 Proxmox VE 支援的儲存類型"]。


NOTE: 當使用 LVM 和 SAN 協定（FC、iSCSI、NVMe-oF）時，磁碟區組可以包含多個 LUN 或 NVMe 命名空間。在這種情況下，所有 LUN 或命名空間都必須屬於同一個一致性群組，以確保資料完整性。我們不支援跨越多個ONTAP SVM 的磁碟區組。每個磁碟區組必須由同一 SVM 中的 LUN 或命名空間建立。



== 選擇儲存協議

選擇符合您環境和要求的協議：

* link:proxmox-ontap-smb.html["配置 SMB/CIFS 存儲"] - 為 Proxmox VE 設定 SMB/CIFS 檔案共享，支援多通道，以實現容錯和增強多網路連線的效能。
* link:proxmox-ontap-nfs.html["配置 NFS 存儲"] - 使用 nConnect 或會話中繼為 Proxmox VE 配置 NFS 存儲，以實現容錯和使用多個網路連接提升效能。
* link:proxmox-ontap-fc.html["使用 FC 配置 LVM"] - 設定邏輯磁碟區管理器 (LVM) 與光纖通道，以實現跨 Proxmox VE 主機的高效能、低延遲區塊儲存存取。
* link:proxmox-ontap-iscsi.html["配置 LVM 與 iSCSI"] - 設定邏輯磁碟區管理器 (LVM) 與 iSCSI，以便透過支援多路徑的標準乙太網路存取區塊儲存。
* link:proxmox-ontap-nvme-fc.html["配置 LVM 與 NVMe/FC"] - 使用現代 NVMe 協議，透過光纖通道配置邏輯磁碟區管理器 (LVM) 和 NVMe，以實現高效能區塊儲存。
* link:proxmox-ontap-nvme-tcp.html["配置 LVM 與 NVMe/TCP"] - 使用現代 NVMe 協議，透過 TCP 設定邏輯磁碟區管理器 (LVM) 和 NVMe，以便在標準乙太網路上實現高效能區塊儲存。

