---
sidebar: sidebar 
permalink: euc/euc-overview.html 
keywords: euc, digital workspace, virtual desktop, vdi, virtual desktop infrastructure, cloud desktop, virtual application, application virtualization, app virtualization, virtual desktop management, desktop management, application management 
summary:  
---
= 了解 NetApp 的終端使用者運算
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
終端使用者運算（EUC）是一種技術，可讓使用者從任何裝置、任何地點存取其桌面和應用程式。採用 NetApp 的 EUC 解決方案包括虛擬桌面基礎架構（VDI）、應用程式虛擬化和使用者設定檔管理。透過 NetApp 的 EUC 解決方案，組織可以提高生產力、降低成本並增強終端使用者的安全性。



[[what-is-end-user-computing-euc]]
== 什麼是終端使用者運算（EUC）？

End User Computing (EUC) 是一種允許使用者隨時隨地透過任何裝置存取其桌面和應用程式的技術。EUC 解決方案通常包括虛擬桌面基礎架構 (VDI)、應用程式虛擬化和使用者設定檔管理工具。透過 EUC，企業可以提高生產力、降低成本並增強終端使用者的安全性。檔案共用和使用者主目錄也是 EUC 解決方案的一部分，使用戶能夠透過任何裝置存取其檔案和資料。

使用者需要存取應用程式來完成工作，無論是透過單一應用程式還是完整的桌面環境。有些使用者可能需要高階圖形應用程式來滿足其桌面工作流程或特定的應用程式使用需求。採用 NetApp 的 EUC 解決方案可以根據每個使用者的需求和要求提供合適的解決方案。透過 NetApp 的 EUC 解決方案，企業可以讓使用者隨時隨地透過任何裝置存取其桌面和應用程式，同時確保資料安全且有效率地儲存。

組織可以選擇將 EUC 解決方案部署在內部部署、雲端或混合式環境中，讓他們能夠靈活選擇最符合其需求的部署模式。透過 NetApp 的 EUC 解決方案，組織可以提高生產力、降低成本並增強終端使用者的安全性，同時也能讓他們靈活地在任何地方工作。



[[high-level-benefits-of-end-user-computing-with-netapp]]
== 使用 NetApp 進行終端使用者運算的高階優勢

NetApp 的 EUC 解決方案為組織提供多項優勢，包括：* 提升生產力：透過 EUC，使用者可以隨時隨地從任何裝置存取其桌面和應用程式，進而提升生產力和協同作業效率。* 降低成本：EUC 可透過集中化桌面和應用程式管理來協助組織降低成本，進而減少對昂貴硬體和軟體的需求。* 增強安全性：EUC 可透過集中化桌面和應用程式管理來協助組織增強安全性，進而降低資料外洩和其他安全事件的風險。* 擴充性：NetApp 的 EUC 解決方案採用可擴充設計，讓組織能夠視需要輕鬆新增或移除使用者。* 靈活度：NetApp 的 EUC 解決方案可部署於內部部署、雲端或混合式環境中，讓組織能夠靈活選擇最符合其需求的部署模式。

如需更多資訊、請查看 link:euc-benefits.html["NetApp 儲存設備對終端使用者運算的優勢"] 頁面。



[[netapps-euc-solutions]]
== NetApp 的 EUC 解決方案

NetApp 提供一系列 EUC 解決方案，包括：* 虛擬桌面基礎架構（VDI）：VDI 解決方案可讓組織向終端使用者提供虛擬桌面，讓他們能夠隨時隨地從任何裝置存取其桌面和應用程式。* 應用程式虛擬化：應用程式虛擬化解決方案可讓組織向終端使用者提供虛擬應用程式，讓他們能夠隨時隨地從任何裝置存取其應用程式。* 檔案共用和主目錄：檔案共用和主目錄解決方案可讓組織為使用者提供隨時隨地從任何裝置存取其檔案和資料的功能，同時確保資料安全且有效率地儲存。* 使用者設定檔管理：使用者設定檔管理解決方案可讓組織跨多個裝置管理使用者設定檔和設定，無論使用者使用何種裝置，都能獲得一致的體驗。
