---
sidebar: sidebar 
permalink: vmware/vmw-vcf-viwld-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= 在 ONTAP 上使用基於 FC 的 VMFS 資料存放區作為 VCF 工作負載網域的主儲存設備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本使用案例概述如何在 ONTAP 上設定 Fibre Channel （FC） VMFS 資料存儲，作為 VMware Cloud Foundation （VCF） 工作負載網域的主儲存設備解決方案。本流程總結了所需的元件、組態步驟和部署流程。



[[benefits-of-fibre-channel]]
== 光纖通道的優勢

*高效能：* FC 提供高速資料傳輸速率，使其成為需要快速可靠地存取大量資料的應用程式的理想選擇。

*低延遲*：非常低的延遲，這對於資料庫和虛擬化環境等效能敏感的應用程式至關重要。

*可靠性：*FC 網路以其穩健性和可靠性而聞名，具有內建冗餘和糾錯等功能。

*專用頻寬：* FC 為儲存流量提供專用頻寬，降低網路擁塞的風險。

有關使用光纖通道與NetApp儲存系統的更多信息，請參閱 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["使用 FC 進行 SAN 配置"]。



[[scenario-overview]]
== 場景概述

此場景涵蓋以下進階步驟：

* 建立具有邏輯介面 (LIF) 的儲存虛擬機器 (SVM) 用於 FC 流量。
* 收集待部署主機的WWPN訊息，並在ONTAP儲存系統上建立對應的啟動器群組。
* 在ONTAP儲存系統上建立 FC 磁碟區。
* 將啟動器群組對應到已建立的 FC Volume。
* 在 FC 交換器上利用單啟動器-目標分區。為每個啟動器建立一個區域（單啟動器區域）。
+
** 對於每個區域，包括一個目標，即 SVM 的ONTAP FC 邏輯介面 (WWPN)。每個 SVM 每個節點應至少有兩個邏輯介面。請勿使用實體連接埠的 WWPN。


* 在 vCenter 中為 vMotion 流量建立網路資源池。
* 在 vCenter 中委任主機以用於工作負載網域。
* 在 VCF Ops 中部署工作負載域，使用 VMFS on FC 資料存放區作為主儲存設備。



NOTE: 此解決方案適用於支援 FC 儲存設備的 ONTAP 平台，包括 NetApp ASAr2、AFF 和 FAS。



[[prerequisites]]
== 先決條件

此場景中使用以下元件和配置：

* 具有 FC 連接埠並連接到 FC 交換器的 ONTAP AFF、ASA 或 FAS 儲存系統。
* 使用 FC lifs 建立的 SVM。
* 帶有 FC HBA 的 vSphere 連接到 FC 交換器。
* 在 FC 交換器上設定單一啟動器-目標分割區。
* 確保 SVM 多路徑原則設定為雙主動式。



NOTE: NetApp建議對 FC LUN 使用多路徑。



[[deployment-steps]]
== 部署步驟



[[vcf-workload-domain-default-cluster]]
=== VCF 工作負載域 - 預設叢集

管理網域啟動並運作後，即可建立 VCF 工作負載域：

* 使用 VCF Ops UI。vSphere 主機已在 vCenter 中委任，且網路資源池已設定。使用 System Manager 或 ONTAP API 將 LUN 部署到 vSphere 主機。
* 將現有 vSphere 環境匯入為新的工作負載域。ONTAP tools for VMware vSphere、System Manager 或 ONTAP API 可用於將 VMFS 資料存放區部署至 vSphere 叢集。




[[vcf-workload-domain-additional-cluster]]
=== VCF 工作負載域 - 附加叢集

若要使用額外的叢集擴充工作負載域，請參閱 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["將 SDDC 叢集新增至 VCF 網域"]。

從高層級來看，為工作負載域新增額外叢集的步驟如下：* 確保主機已完成部署，且網路資源池已在 vCenter 中完成設定。* 在 ONTAP 儲存系統上佈建 LUN，並將其呈現給額外叢集中的主機。* 在 vCenter 上的工作負載域中建立新的 SDDC 叢集，並依照精靈指引將額外叢集新增至工作負載域。



[[additional-information]]
== 附加資訊

有關配置ONTAP儲存系統的信息，請參閱link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文件"]中心。

有關設定 VCF 的資訊，請參閱 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 雲端基礎文檔"]。
