---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage, workload 
summary: 'VMware Cloud Foundation (VCF) 支援多種補充儲存設備選項，以擴充 VCF 管理網域和工作負載網域上的儲存設備。' 
---
= 了解如何使用補充存儲擴展 VCF 環境的存儲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware Cloud Foundation (VCF) 支援多種補充儲存設備選項，以擴充 VCF 管理網域和工作負載網域上的儲存設備。

NetApp 的ONTAP tools for VMware vSphere透過將NetApp儲存無縫整合到 VCF 環境中，為此擴充提供了有效的解決方案。

ONTAP工具簡化了資料儲存區的設定和管理，讓管理員可以直接從 vSphere Client 配置和管理儲存。  ONTAP 的進階功能（例如快照、複製和資料保護）可增強 VCF 環境內的儲存效能、效率和可擴充性。



[[supported-protocols-for-expanding-storage]]
== 擴充儲存支援的協議

VCF 環境可以使用多種儲存協定進行擴展，每種協定都提供獨特的優勢和用例。

您可以使用下列協定來擴充 VCF 管理域和工作負載域中的儲存設備。選擇最適合您環境的方案，將補充儲存設備無縫地整合到 VCF 部署中。

.iSCSI
使用標準乙太網路的基於區塊的協定。非常適合需要高性能、靈活性和經濟高效擴展的環境。

iSCSI 廣泛用於 VMFS 資料存放區，並支援 ONTAP 的進階功能，例如快照和複製。ONTAP 9.19.1 及更新版本也支援 AFF 系統上的對稱雙主動式組態。最初，此功能僅適用於 ASA 系統。

* *高效能：*提供高效能，以實現快速、高效的資料傳輸速率和低延遲。非常適合要求嚴格的企業應用程式和虛擬化環境。
* *易於管理：*透過使用熟悉的基於 IP 的工具和協定簡化儲存管理。
* *成本效益：*使用現有的乙太網路基礎設施，減少對專用硬體的需求，並允許組織實現可靠且可擴展的儲存解決方案。


有關將 iSCSI 與NetApp儲存系統結合使用的更多信息，請參閱 https://docs.netapp.com/us-en/ontap/san-admin/san-host-provisioning-concept.html["使用 iSCSI 進行 SAN 配置"]。

.光纖通道（FC）
使用專用 FC 網路的高速、低延遲協定。對於需要可靠性、專用頻寬和強大糾錯能力的關鍵任務工作負載來說，FC 是首選。它通常用於企業環境中的 VMFS 資料儲存。

ONTAP 9.19.1 及更高版本也支援 AFF 系統上的對稱雙主動式組態。最初，此功能僅適用於 ASA 系統。

* *高效能：* FC 提供高速資料傳輸速率，使其成為需要快速可靠地存取大量資料的應用程式的理想選擇。
* *低延遲*：非常低的延遲，這對於資料庫和虛擬化環境等效能敏感的應用程式至關重要。
* *可靠性：*FC 網路以其穩健性和可靠性而聞名，具有內建冗餘和糾錯等功能。
* *專用頻寬：* FC 為儲存流量提供專用頻寬，降低網路擁塞的風險。


有關使用光纖通道與NetApp儲存系統的更多信息，請參閱 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["使用 FC 進行 SAN 配置"]。

.NFS（網路檔案系統）
基於文件的協議，可輕鬆實現跨主機的文件共享和管理。  NFS 設定簡單且擴充高效，適用於需要靈活檔案存取的虛擬化工作負載和環境。

ONTAP和 vSphere 支援用於管理網域和工作負載域的 NFS 資料儲存庫。

* *簡單易用：*NFS 設定和管理簡單，使其成為需要快速簡單的文件共享環境的絕佳選擇。
* *擴充性：* ONTAP 的架構可讓 NFS 有效率地擴充，在無需對基礎架構進行重大變更的情況下，支援不斷增長的資料需求。FlexGroup 結合 pNFS，可將 NFS 資料存放區擴充至 PB 等級。
* *靈活性*：NFS 支援廣泛的應用程式和工作負載，使其適用於各種用例，包括虛擬化環境。


欲了解更多信息，請參閱link:vmw-vvf-overview.html["適用於 vSphere 8 的 NFS v3 參考指南"] 。

.NVMe-oF
現代協議，可透過 TCP/IP 在標準乙太網路網路上提供高效能與低延遲。NVMe-oF（NVMe over Fabrics）非常適合高要求的應用程式和大規模資料作業，無需專用硬體即可提供擴充性與成本效率。

ONTAP 9.19.1 及更高版本也支援 AFF 系統上的對稱雙主動式組態。最初，此功能僅適用於 ASA 系統。

* *高效能：*以低延遲和高資料傳輸速率提供卓越的效能。這對於要求嚴格的應用程式和大規模資料操作至關重要。
* *可擴充性：*支援可擴充配置，讓 IT 管理員隨著資料需求的成長無縫擴展其基礎架構。
* *經濟高效：*可在標準乙太網路交換器上運行，並封裝在 TCP 資料報中。無需特殊設備即可實作。NVMe-oF over TCP 是一種常用方案。


有關 NVMe 優勢的更多信息，請參閱 https://www.netapp.com/data-storage/nvme/what-is-nvme/["什麼是 NVME？"]。



[[use-cases-for-adding-supplemental-storage]]
== 新增補充儲存的用例

以下用例示範如何使用不同的協定和配置為 VCF 管理域和虛擬基礎架構 (VI) 工作負載域新增補充儲存。

* link:vmw-vcf-mgmt-supplemental-iscsi.html["具有 iSCSI 的管理域"]
* link:vmw-vcf-mgmt-supplemental-fc.html["帶有 FC 的管理域"]
* link:vmw-vcf-viwld-supp-iscsi-vvols.html["具有vVols (iSCSI) 的虛擬基礎架構工作負載域"]
* link:vmw-vcf-viwld-supp-nfs-vvols.html["具有vVols (NFS) 的虛擬基礎架構工作負載域"]
* link:vmw-vcf-viwld-supp-nvme.html["具有 NVMe/TCP 的虛擬基礎架構工作負載域"]
* link:vmw-vcf-viwld-supp-fc.html["具有 FC 的虛擬基礎架構工作負載域"]

