---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-nfs-requirements.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, nfs, array, ontap tools, otv, sddc, sddc manager, ontap tools, ontap tools 10 
summary: 檢閱將具有 NetApp ONTAP NFS 資料存放區的 vSphere 叢集聚合至 VMware Cloud Foundation 管理網域的需求。 
---
= 使用 NFS 資料存放區將 vCenter 伺服器執行個體整合到 VCF 管理網域的部署需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
檢閱將具有 NetApp ONTAP NFS 資料存放區的 vSphere 叢集聚合至 VMware Cloud Foundation 管理網域的需求。

融合程序需要 AFF 或 AFX 儲存系統、用於 NFS 流量的 SVM 和 LIF、交換器上的 NFS VLAN、具有 vSphere 主機的 vSphere 叢集和 vCenter，以及 vMotion 的專用網路區段。



[[infrastructure-requirements]]
== 基礎設施需求

確保以下組件和配置已到位。

* NetApp AFF 或 AFX 儲存系統，並設定儲存虛擬機器 （SVM） 以允許 NFS 流量。
* 在 IP 網路上建立的用於承載 NFS 流量並與 SVM 關聯的邏輯介面 (LIF)。
* 一個 vSphere 叢集，其中至少包含 2 台 vSphere 主機，以及一個共同位於該叢集上的 vCenter 應用裝置。
* 為 vMotion 和 NFS 儲存流量在為此目的建立的 VLAN 或網路區段上配置的分散式連接埠群組。
* VCF 安裝程式工具，用於將 vCenter 融合至 VCF 管理網域。
* ONTAP工具的先決條件。
+
有關ONTAP工具前提條件的完整信息，請參閱 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/prerequisites.html#system-requirements["適用於ONTAP tools for VMware vSphere的先決條件"]。

+
ONTAP tools for VMware vSphere可以安裝在 HA 或非 HA 配置中。





[[additional-resources]]
== 其他資源

* 有關支援儲存設備和其他將 vSphere 融合至 VCF 的相關注意事項，請參閱 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/deployment/converging-your-existing-vsphere-infrastructure-to-a-vcf-or-vvf-platform-/supported-and-not-supported-configurations.html["趨向 VCF 的支援和不支援組態"]。
* 有關配置ONTAP儲存系統的信息，請參閱link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文件"]。
* 有關設定 VCF 的資訊，請參閱link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware Cloud Foundation 9.1 文件"]。




[[whats-next]]
== 下一步是什麼？

查看部署要求後，link:vmw-vcf-mgmt-nfs-deploy.html["部署ONTAP工具並配置 NFS 資料儲存庫"] 。
