---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= 使用ONTAP上基於 FC 的 VMFS 資料儲存庫作為 VCF 管理域的主要存儲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
本使用案例概述在 ONTAP 上建立 FC 型 VMFS 資料儲存區作為 VMware Cloud Foundation （VCF） 管理網域主儲存設備的步驟。本步驟總結所需的元件、組態及部署步驟。



[[introduction]]
== 介紹

在適當情況下，我們將參考外部文件，以了解必須在 vCenter 中執行的步驟，並參考儲存組態部分特有的步驟。

有關在含有 ONTAP 的 vSphere 環境中轉換現有 VMFS 資料存放區（包括 iSCSI 和 NVMe-oF）的資訊，請參閱link:vmw-vcf-mgmt-vmfs.html["將 vSphere 環境（VMFS 資料儲存）融合至 VCF 管理網域"]。


NOTE: VCF 5.2 版本引進了將現有 vSphere 8 環境轉換為 VCF 管理網域或匯入為 VCF VI 工作負載網域的功能。在此版本之前，VMware vSAN 是 VCF 管理網域主儲存設備的唯一選擇。NSX 控制器虛擬機器最好部署在基於 FC 的 VMFS 資料儲存區上，或使用雙網路交換器以避免單點故障。如果這些選項無法使用，請考慮使用 vSAN 來裝載這些虛擬機器。


NOTE: 此解決方案適用於支援FC儲存的ONTAP平台，包括NetApp ASA、 AFF和FAS。



[[prerequisites]]
== 先決條件

此場景中使用以下元件和配置：

* NetApp儲存系統配置了儲存虛擬機器 (SVM) 以允許 FC 流量。
* 已在 FC 結構上建立用於承載 FC 流量並與 SVM 關聯的邏輯介面 (LIF)。
* 分區已配置為在 FC 交換器上使用單一啟動器-目標分區，用於主機 HBA 和儲存目標。
* 在叢集中的其中一台 vSphere 主機上建立 VMFS 資料存放區（含 FC LUN）。


有關配置ONTAP儲存系統的信息，請參閱link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文件"]中心。

有關設定 VCF 的資訊，請參閱 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 雲端基礎文檔"]。



[[deployment-steps]]
== 部署步驟



[[management-domain-default-cluster]]
=== 管理域 - 預設集群

VCF 安裝程式工具支援管理網域的 VMFS on FC、NFS v3 和 vSAN 資料儲存。以下步驟概述如何部署以 ONTAP 上的 FC 型 VMFS 資料儲存作為主儲存設備的管理網域。

有關使用現有 vSphere 環境的詳細資訊，請參閱 link:vmw-vcf-mgmt-vmfs.html["將 vSphere 環境（VMFS 資料儲存）融合至 VCF 管理網域"]。



[[management-domain-additional-cluster]]
=== 管理域 - 附加集群

若要使用額外的叢集擴充管理域，請參閱 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1/building-your-private-cloud-infrastructure/working-with-workload-domains/expand-a-workload-domain/add-a-cluster-to-a-workload-domain-using-the-sddc-manager-ui.html["將 SDDC 叢集新增至 VCF 網域"]。

從整體來看，為管理網域新增額外叢集的步驟如下：* 確保主機已完成部署，且網路池已在 vCenter 中設定。* 在 ONTAP 儲存系統上配置 LUN，並呈現給額外叢集中的主機。* 在 vCenter 上的管理網域中建立新的 SDDC 叢集，並依照精靈將額外叢集新增至管理網域。



[[reference-video]]
== 參考影片

.採用 FC 的主資料存放區
video::9c51101c-292b-41ef-8dd5-b4cf0131dd62[panopto,width=360]


[[additional-information]]
== 附加資訊

有關配置ONTAP儲存系統的信息，請參閱link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文件"]中心。

有關設定 VCF 的資訊，請參閱 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-9-0-and-later/9-1.html["VMware 雲端基礎文檔"]。
