---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-supplemental-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= 使用適用ONTAP tools for VMware vSphere新增基於 FC 的 VMFS 資料儲存庫作為管理域的補充存儲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此用例中，我們概述了使用ONTAP Tools for VMware 透過光纖通道 (FC) 配置 VMFS 資料儲存作為 VMware Cloud Foundation (VCF) 管理域的補充儲存的過程。此過程總結了為 VMware vSphere 部署ONTAP工具、註冊 vCenter 伺服器、定義儲存後端以及配置 FC 資料儲存庫。



== 光纖通道的優勢

*高效能：* FC 提供高速資料傳輸速率，使其成為需要快速可靠地存取大量資料的應用程式的理想選擇。

*低延遲*：非常低的延遲，這對於資料庫和虛擬化環境等效能敏感的應用程式至關重要。

*可靠性：*FC 網路以其穩健性和可靠性而聞名，具有內建冗餘和糾錯等功能。

*專用頻寬：* FC 為儲存流量提供專用頻寬，降低網路擁塞的風險。

有關使用光纖通道與NetApp儲存系統的更多信息，請參閱 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["使用 FC 進行 SAN 配置"]。



== 場景概述

VCF 補充資料儲存是使用 vCenter 作為第二天操作的一部分提供的。此場景涵蓋以下進階步驟：

* 在管理域上部署ONTAP工具
* 向ONTAP工具註冊 VI 工作負載 vCenter 伺服器
* 在適用於 VMware vSphere 的ONTAP工具外掛程式上定義儲存後端
* 在 FC 傳輸上配置 VMFS




== 先決條件

此場景需要以下組件和配置：

* 具有連接到 FC 交換器的 FC 連接埠的ONTAP儲存系統。
* 使用 FC lifs 建立的 SVM。
* 帶有 FC HBA 的 vSphere 連接到 FC 交換器。
* 在 FC 交換器上設定單一啟動器-目標分割區。
+

NOTE: 在區域配置中使用 SVM FC 邏輯接口，而不是ONTAP系統上的實體 FC 連接埠。



NetApp建議對 FC LUN 使用多路徑。

有關在ONTAP儲存系統上配置光纖通道的完整信息，請參閱 https://docs.netapp.com/us-en/ontap/san-management/index.html["SAN儲存管理"]在ONTAP 9 文檔中。

有關將 VMFS 與ONTAP儲存系統結合使用的更多信息，請參閱link:vmw-vmfs-deploy.html["VMFS 部署指南"]。



== 管理域的部署步驟

若要部署ONTAP工具並使用它在 VCF 管理網域上建立 VMFS 資料儲存庫，請完成下列步驟：

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["在管理域上部署ONTAP工具"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["使用 vSphere 用戶端介面定義儲存後端"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-datastore.html["在 FC 上配置 VMFS"]




== 附加資訊

有關配置ONTAP儲存系統的信息，請參閱link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文件"]中心。

有關配置 VCF 的信息，請參閱link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware 雲端基礎文檔"]。



== 此解決方案的視訊演示

.VMFS（FC）資料儲存作為VCF管理域的補充存儲
video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto,width=360]