---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-otv.html 
keywords: vmware, getting, started, overview, netapp, otv, ontap, tools 
summary:  
---
= 了解如何使用適用ONTAP tools for VMware vSphere管理虛擬機
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphere 精簡了使用 NetApp 儲存設備的 VM 生命週期管理。管理員可以直接從 vCenter Server 管理儲存設備，從而簡化作業並增強擴充性。諸如 vSphere Client 外掛、VASA Provider 及 Storage Replication Adapter （SRA） 等關鍵元件，可最佳化資源配置、效能監控與災難恢復。



[[introduction]]
== 介紹

它使管理員能夠直接管理 vCenter Server 內的存儲，並簡化 VMware 環境的儲存和資料管理。 VMware vSphere Client 外掛程式工具旨在將外掛功能整合到 vSphere Client 中，而無需在 vCenter Server 內部執行。這提供了插件隔離並支援在大型 vSphere 環境中運行的插件的橫向擴展。



[[ontap-tools-components]]
== ONTAP工具元件

* *vSphere 用戶端外掛* 該外掛包含與 vSphere 用戶端整合的介面，您可以透過該介面新增儲存設備控制器、資源配置資料儲存區、監控資料儲存區的效能，以及檢視和更新 ESXi 主機設定。在 ONTAP tools 9.x 中，此元件稱為 Virtual Storage Console（VSC）。
* *VASA 提供者* 適用於ONTAP 的VMware vSphere APIs for Storage Awareness (VASA) 提供者將有關 VMware vSphere 使用的儲存的資訊傳送至 vCenter Server，從而實現 VMware 虛擬磁碟區 (vVols) 資料儲存的設定、儲存功能設定檔的建立與使用、合規性
* *儲存複製適配器 (SRA)* 啟用並與 VMware Site Recovery Manager (SRM) 一起使用時，SRA 可在發生故障時促進 vCenter Server 資料儲存和虛擬機器的恢復，從而允許配置受保護網站和復原網站以進行災難復原。


如需詳細資訊，請參閱適用於您版本的 ONTAP tools for VMware vSphere 文件：

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/index.html["ONTAP tools for VMware vSphere 10.x 文件"^]（最新版本）
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["ONTAP tools for VMware vSphere 9.x 文件"^]

