---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-principal-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= 使用ONTAP上基於 FC 的 VMFS 資料儲存庫作為 VCF 管理域的主要存儲
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在此用例中，我們概述了使用ONTAP上現有的基於 FC 的 VMFS 資料儲存作為 VMware Cloud Foundation (VCF) 管理域的主儲存的過程。此過程總結了所需的元件、配置和部署步驟。



== 介紹

在適當的情況下，我們將參考外部文檔，以了解必須在 VCF 的 SDDC 管理器中執行的步驟，並參考特定於儲存配置部分的步驟。

有關使用ONTAP轉換現有基於 FC 的 vSphere 環境的信息，請參閱link:vmw-vcf-mgmt-fc.html["將 vSphere 環境（FC 資料儲存）轉換為 VCF 管理域"]。


NOTE: VCF 版本 5.2 引進了將現有 vSphere 8 環境轉換為 VCF 管理域或匯入為 VCF VI 工作負載域的功能。在此版本之前，VMware vSAN 是 VCF 管理域的主要儲存的唯一選項。


NOTE: 此解決方案適用於支援FC儲存的ONTAP平台，包括NetApp ASA、 AFF和FAS。



== 先決條件

此場景中使用以下元件和配置：

* NetApp儲存系統配置了儲存虛擬機器 (SVM) 以允許 FC 流量。
* 已在 FC 結構上建立用於承載 FC 流量並與 SVM 關聯的邏輯介面 (LIF)。
* 分區已配置為在 FC 交換器上使用單一啟動器-目標分區，用於主機 HBA 和儲存目標。


有關配置ONTAP儲存系統的信息，請參閱link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文件"]中心。

有關配置 VCF 的信息，請參閱link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware 雲端基礎文檔"]。



== 部署步驟



=== 管理域 - 預設集群

初始叢集上的 FC 主儲存僅支援 VCF 棕地匯入工具。如果使用 Cloud Builder 工具（版本 5.2.x 之前的版本）部署 VCF，則僅支援 vSAN。

有關使用現有 vSphere 環境的更多信息，請參閱 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["將現有 vSphere 環境轉換為管理域"]了解更多。



=== 管理域 - 附加集群

管理網域上的附加 vSphere 叢集可以透過下列選項進行部署：

* 在 vSphere 環境中擁有額外的集群，並使用 VCF 棕地導入工具將 vSphere 環境轉換為管理域。 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["ONTAP tools for VMware vSphere"] https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["系統管理員或ONTAP API"]可用於將 VMFS 資料儲存部署到 vSphere 叢集。
* 使用 SDDC API 部署額外的叢集。 vSphere 主機應該配置 VMFS 資料儲存。使用 https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["系統管理員或ONTAP API"]將 LUN 部署到 vSphere 主機。
* 使用 SDDC Manager UI 部署額外的叢集。但此選項僅建立 VSAN 資料儲存至 5.2.x 版本。




== 附加資訊

有關配置ONTAP儲存系統的信息，請參閱link:https://docs.netapp.com/us-en/ontap["ONTAP 9 文件"]中心。

有關配置 VCF 的信息，請參閱link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware 雲端基礎文檔"]。
